[monitor:///var/log/syslog]
disabled = 0
sourcetype = syslog

[monitor:///var/log/auth.log]
disabled = 0
sourcetype = auth_log

[monitor:///var/log/kern.log]
disabled = 0
sourcetype = kern_log

[monitor:///var/log/dpkg.log]
disabled = 0
sourcetype = dpkg_log

[monitor:///etc/passwd]
disabled = 0
sourcetype = passwd_file

[monitor:///etc/hosts]
disabled = 0
sourcetype = hosts_file

[monitor://$SPLUNK_HOME/var/log/splunk/splunkd.log]
disabled = 0
index = _internal

[monitor://$SPLUNK_HOME/var/log/splunk/metrics.log]
disabled = 0
index = _internal
